name: FastAPI CI/CD

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_TEST_EC2_IP }}
          username: ${{ secrets.AWS_TEST_EC2_USER }}
          key: ${{ secrets.AWS_TEST_EC2_SSH_KEY }}
          script: |
            export PATH="$HOME/.local/bin:$PATH"
            cd /home/ubuntu/fastapi-cicd-demo
            git pull origin dev
            pm2 restart fastapi-app-dev