name: FastAPI CI/CD

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: ssh into ec2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_TEST_EC2_IP }}
          username: ${{ secrets.AWS_TEST_EC2_USER }}
          key: ${{ secrets.AWS_TEST_EC2_SSH_KEY }}
          script: |
              export PATH="$HOME/.local/bin:$PATH"
              cd /var/www/fastapi-app
              git pull origin dev
              pm2 restart 0
                
          
